server:
  port: 9007  #服务端口号

spring:
  application:
    name: pms-eseal # 注册服务名
  datasource:
    url: jdbc:mysql://192.168.20.16:3306/pms_eseal?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: kmc
    password: kmc
    driver-class-name: com.mysql.cj.jdbc.Driver
    connectionTimeout: 300
    maxIdleTime: 600
    maxPoolSize: 10
    initialization-mode: always # always : 始终执行初始化
    schema: classpath*:/sql/db_structure.sql # 初始化表结构
    #data: classpath*:/sql/db_init_data.sql # 初始化数据
    continue-on-error: true # 遇到语句错误时是否继续(创建相同表/导入相同数据会报错，因此设置为true)
  redis:
    database: 0  # Redis数据库索引（默认为0）
    host: 192.168.20.134 # Redis服务器地址
    port: 6379  # Redis服务器连接端口
    password:  # Redis服务器连接密码（默认为空）
    timeout: 0ms # 连接超时时间（毫秒）
    jedis:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接

# mybatis-plus 配置
mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml


#自定义配置
user:
  define:
    crypto:
      useToken: false
      makerkeyfile: maker.pfx
      password: yunjingit
      alias: privateKey
    cert:
      name: 云京科技Paas平台
      id: 91110105061311021A
      phone: 13811400000
      email: support@yunjingit.com
      image: 77777777
      type: 2
      userId: pms-eseal
    pic:
      round: 40
      ovalw: 45
      ovalh: 30
      recw: 18
      rech: 18
    esid:
      prefix: ESP
